<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends EntityRepository
{
    public function findCliente($m, $p){

        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
            ->select('c')
            ->from('FrontBundle:Cliente','c')
            ->leftJoin('c.mascotas', 'e')
            ->where('c.nombre LIKE :p AND e.nombre LIKE :m')
            ->setParameter('p', '%'.$p.'%')
            ->setParameter('m', '%'.$m.'%')
            ->getQuery();
        return $queryBuilder->getResult();
    }
}
