<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EspecieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspecieRepository extends EntityRepository
{
    public function findEspecie($param){
        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
            ->select('e')
            ->from('FrontBundle:Especie','e')
            ->where('e.nombre LIKE :param')
            ->setParameter('param', '%'.$param.'%')
            ->getQuery();
        return $queryBuilder->getResult();
    }
}
