<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MascotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MascotaRepository extends EntityRepository
{
    public function findMascota($m, $p){

        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
            ->select('e')
            ->from('FrontBundle:Mascota','e')
            ->leftJoin('e.clientes', 'c')
            ->where('e.nombre LIKE :m AND c.nombre LIKE :p')
            ->setParameter('m', '%'.$m.'%')
            ->setParameter('p', '%'.$p.'%')
            ->getQuery();
        return $queryBuilder->getResult();
    }
}
