<?php

namespace AppBundle\Entity;

/**
 * ReferenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
