<?php

namespace AppBundle\Entity;

/**
 * TipoContactosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoContactosRepository extends \Doctrine\ORM\EntityRepository
{
}
