<?php

namespace AppBundle\Entity;

/**
 * UbigeosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UbigeosRepository extends \Doctrine\ORM\EntityRepository
{

    public function elementosDep($idpais){
    $queryBuilder = $this->getEntityManager()->createQueryBuilder()
        ->select('DISTINCT a.iddep, a.departamento')
        ->from('AppBundle:Ubigeos', 'a')
        ->where('a.idpais = :idpais')
        ->setParameter('idpais',$idpais)
        ->getQuery();

    return $queryBuilder->getResult();
}
    public function ubigeoByIds($idpais, $iddep, $idprov, $iddist ){
        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
            ->select('a')
            ->from('AppBundle:Ubigeos', 'a')
            ->where('a.idpais = :idpais AND a.iddep = :iddep AND a.idprov =:idprov AND a.iddist =:iddist')
            ->setParameter('idpais',$idpais)
            ->setParameter('iddep',$iddep)
            ->setParameter('idprov',$idprov)
            ->setParameter('iddist',$iddist)
            ->getQuery();

        return $queryBuilder->getOneOrNullResult();
    }
    public function elementosProv($idpais, $iddep){
        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
            ->select('DISTINCT a.idprov, a.provincia')
            ->from('AppBundle:Ubigeos', 'a')
            ->where('a.idpais = :idpais AND a.iddep = :iddep')
            ->setParameter('idpais',$idpais)
            ->setParameter('iddep',$iddep)
            ->getQuery();

        return $queryBuilder->getResult();
    }
    public function elementosDist($idpais, $iddep, $idprov){
        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
            ->select('DISTINCT a.iddist, a.distrito')
            ->from('AppBundle:Ubigeos', 'a')
            ->where('a.idpais = :idpais AND a.iddep = :iddep AND a.idprov =:idprov')
            ->setParameter('idpais',$idpais)
            ->setParameter('iddep',$iddep)
            ->setParameter('idprov',$idprov)
            ->getQuery();

        return $queryBuilder->getResult();
    }

    public function getPaisPadre(){
        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
            ->select ('DISTINCT a.idpais, a.pais')
            ->from('AppBundle:Ubigeos', 'a')
            ->getQuery();

        return $queryBuilder->getResult();
    }

}
